INSERT INTO Product (Product_ID, Name, Description, Price, Stock_Quantity, Category) VALUES
    (1, 'Taisan Soft Cake', NULL, NULL, 0, 'Bread'),
    (2, 'Ubeng Ube Loaf', NULL, NULL, 5, 'Bread'),
    (3, 'Pandecoconut', NULL, NULL, 12, 'Bread'),
    (4, 'Pande esapana', NULL, NULL, 8, 'Bread'),
    (5, 'Mamon Cup', NULL, NULL, 10, 'Bread'),
    (6, 'Delightful Treats Choco', NULL, NULL, 7, 'Bread'),
    (7, 'Crinkles Cokie', NULL, NULL, 6, 'Bread'),
    (8, 'Pinoy Tasty', NULL, NULL, 15, 'Bread'),
    (9, 'Jumbo Sandwich Loaf', NULL, NULL, 6, 'Bread'),
    (10, 'Wheat Bread', NULL, NULL, 5, 'Bread'),
    (11, 'Egg Pie Leche Plan', NULL, NULL, 0, 'Pastry'),
    (12, 'Brownie Bites', NULL, NULL, 3, 'Pastry'),
    (13, 'Custard Surprise', NULL, NULL, 9, 'Pastry'),
    (14, 'Cluster Ensaymada Ube with Cheese', NULL, NULL, 11, 'Pastry'),
    (15, 'Mini Cinamon Roll', NULL, NULL, 5, 'Pastry'),
    (16, 'Ensaymada Cheese', NULL, NULL, 10, 'Pastry'),
    (17, 'Snap n’ roll', NULL, NULL, 8, 'Pastry'),
    (18, 'Cheesy Ensaymada', NULL, NULL, 9, 'Pastry'),
    (19, 'Egg pie caramel', NULL, NULL, 14, 'Pastry'),
    (20, 'Cheesy Butter Softy', NULL, NULL, 18, 'Pastry'),
    (21, 'Mamon', NULL, NULL, 6, 'Pastry'),
    (22, 'Choco Bar', NULL, NULL, 7, 'Pastry'),
    (23, 'Ensaymada Ube', NULL, NULL, 11, 'Pastry'),
    (24, 'Choco Cherry Cake', NULL, NULL, 0, 'Cakes'),
    (25, 'Creamy Choco Cake', NULL, NULL, 2, 'Cakes'),
    (26, 'Chocolate Cake', NULL, NULL, 10, 'Cakes'),
    (27, 'Moist Cake', NULL, NULL, 14, 'Cakes'),
    (28, 'Pastel Delight Round Cake', NULL, NULL, 9, 'Cakes'),
    (29, 'Mocha Celebration Cake Round', NULL, NULL, 8, 'Cakes'),
    (30, 'Junior Cake, Ube Temptation', NULL, NULL, 9, 'Cakes'),
    (31, 'Choco Celebration On Cake Round', NULL, NULL, 7, 'Cakes'),
    (32, 'Yema Round Celebration On Cake', NULL, NULL, 9, 'Cakes'),
    (33, 'Choco Caramel Cake', NULL, NULL, 7, 'Cakes'),
    (34, 'Mocha Celebration On Cake Rectangle', NULL, NULL, 6, 'Cakes'),
    (35, 'Ube Macapuno Cake', NULL, NULL, 6, 'Cakes'),
    (36, 'Yema Rectangle Celebration On Cake', NULL, NULL, 4, 'Cakes'),
    (37, 'Roll Choco Fudge', NULL, NULL, 8, 'Cakes'),
    (38, 'Roll, Ube Macapuno', NULL, NULL, 14, 'Cakes'),
    (39, 'Roll, Nutty Caramel Cake', NULL, NULL, 18, 'Cakes'),
    (40, 'Junior Cake, Mango Cream Deluxe', NULL, NULL, 12, 'Cakes'),
    (41, 'Choco Celebration On Cake Rectangle', NULL, NULL, 13, 'Cakes'),
    (42, 'Butterfly Sanctuary', NULL, NULL, NULL, 'Cakes'),
    (43, 'Beauty Cake', NULL, NULL, NULL, 'Cakes'),
    (44, 'Space Adventure', NULL, NULL, NULL, 'Cakes'),
    (45, 'Glitz’n Glam Cake', NULL, NULL, NULL, 'Cakes'),
    (46, 'Flamingo Cake', NULL, NULL, NULL, 'Cakes'),
    (47, 'Enchanted Cake', NULL, NULL, NULL, 'Cakes'),
    (48, 'Candy Drizzle Cake', NULL, NULL, NULL, 'Cakes'),
    (49, 'Cat Castle Cake', NULL, NULL, NULL, 'Cakes'),
    (50, 'Peppa Cake', NULL, NULL, NULL, 'Cakes'),
    (51, 'Ice Cream Heaven Cake', NULL, NULL, NULL, 'Cakes'),
    (52, 'Rainbow Unicorn', NULL, NULL, NULL, 'Cakes'),
    (53, 'Princess Cake', NULL, NULL, NULL, 'Cakes'),
    (54, 'Blooming Flower Cake', NULL, NULL, NULL, 'Cakes'),
    (55, 'Elephant Cake', NULL, NULL, NULL, 'Cakes'),
    (56, 'Racers Cake', NULL, NULL, NULL, 'Cakes'),
    (57, 'Detective Cake', NULL, NULL, NULL, 'Cakes'),
    (58, 'Nautical Cake', NULL, NULL, NULL, 'Cakes'),
    (59, 'Sea Adventure Cake', NULL, NULL, NULL, 'Cakes'),
    (60, 'Jungle Explore Cake', NULL, NULL, NULL, 'Cakes'),
    (61, 'Nursery Cake', NULL, NULL, NULL, 'Cakes'),
    (62, 'Spider Web Cake', NULL, NULL, NULL, 'Cakes'),
    (63, 'Unicorn Cake', NULL, NULL, NULL, 'Cakes'),
    (64, 'Sonic Speed Cake', NULL, NULL, NULL, 'Cakes'),
    (65, 'Minecraft Kindom Cake', NULL, NULL, NULL, 'Cakes'),
    (66, 'Build The Party', NULL, NULL, NULL, 'Cakes');

INSERT INTO Inventory (Product_ID, Stock_Quantity) VALUES
    (1, 0),
    (2, 5),
    (3, 12),
    (4, 8),
    (5, 10),
    (6, 7),
    (7, 6),
    (8, 15),
    (9, 6),
    (10, 5),
    (11, 0),
    (12, 3),
    (13, 9),
    (14, 11),
    (15, 5),
    (16, 10),
    (17, 8),
    (18, 9),
    (19, 14),
    (20, 18),
    (21, 6),
    (22, 7),
    (23, 11),
    (24, 0),
    (25, 2),
    (26, 10),
    (27, 14),
    (28, 9),
    (29, 8),
    (30, 9),
    (31, 7),
    (32, 9),
    (33, 7),
    (34, 6),
    (35, 6),
    (36, 4),
    (37, 8),
    (38, 14),
    (39, 18),
    (40, 12),
    (41, 13),
    (42, NULL),
    (43, NULL),
    (44, NULL),
    (45, NULL),
    (46, NULL),
    (47, NULL),
    (48, NULL),
    (49, NULL),
    (50, NULL),
    (51, NULL),
    (52, NULL),
    (53, NULL),
    (54, NULL),
    (55, NULL),
    (56, NULL),
    (57, NULL),
    (58, NULL),
    (59, NULL),
    (60, NULL),
    (61, NULL),
    (62, NULL),
    (63, NULL),
    (64, NULL),
    (65, NULL),
    (66, NULL);
