INSERT INTO Product (Product_ID, Name, Description, Price, Stock_Quantity, Category, Image_Path) VALUES
    (1, 'Taisan Soft Cake', NULL, NULL, 0, 'Bread', NULL),
    (2, 'Ubeng Ube Loaf', NULL, NULL, 5, 'Bread', 'bread2.png'),
    (3, 'Pandecoconut', NULL, NULL, 12, 'Bread', 'bread3.png'),
    (4, 'Pande esapana', NULL, NULL, 8, 'Bread', 'bread4.png'),
    (5, 'Mamon Cup', NULL, NULL, 10, 'Bread', 'bread6.png'),
    (6, 'Delightful Treats Choco', NULL, NULL, 7, 'Bread', 'bread7.png'),
    (7, 'Crinkles Cokie', NULL, NULL, 6, 'Bread', NULL),
    (8, 'Pinoy Tasty', NULL, NULL, 15, 'Bread', 'bread8.png'),
    (9, 'Jumbo Sandwich Loaf', NULL, NULL, 6, 'Bread', 'bread9.png'),
    (10, 'Wheat Bread', NULL, NULL, 5, 'Bread', 'bread10.png'),
    (11, 'Egg Pie Leche Plan', NULL, NULL, 0, 'Pastry', 'pastry5.png'),
    (12, 'Brownie Bites', NULL, NULL, 3, 'Pastry', 'pastry6.png'),
    (13, 'Custard Surprise', NULL, NULL, 9, 'Pastry', 'pastry3.png'),
    (14, 'Cluster Ensaymada Ube with Cheese', NULL, NULL, 11, 'Pastry', 'pastry7.png'),
    (15, 'Mini Cinamon Roll', NULL, NULL, 5, 'Pastry', 'pastry9.png'),
    (16, 'Ensaymada Cheese', NULL, NULL, 10, 'Pastry', 'pastry8.png'),
    (17, 'Snap n’ roll', NULL, NULL, 8, 'Pastry', 'pastry10.png'),
    (18, 'Cheesy Ensaymada', NULL, NULL, 9, 'Pastry', 'pastry8.png'),
    (19, 'Egg pie caramel', NULL, NULL, 14, 'Pastry', 'pastry4.png'),
    (20, 'Cheesy Butter Softy', NULL, NULL, 18, 'Pastry', 'pastry1.png'),
    (21, 'Mamon', NULL, NULL, 6, 'Pastry', 'bread6.png'),
    (22, 'Choco Bar', NULL, NULL, 7, 'Pastry', 'pastry2.png'),
    (23, 'Ensaymada Ube', NULL, NULL, 11, 'Pastry', 'pastry11.png'),
    (24, 'Choco Cherry Cake', NULL, NULL, 0, 'Cakes', 'Compressed images/cake3.png'),
    (25, 'Creamy Choco Cake', NULL, NULL, 2, 'Cakes', 'Compressed images/cake2.png'),
    (26, 'Chocolate Cake', NULL, NULL, 10, 'Cakes', 'Compressed images/cake8.png'),
    (27, 'Moist Cake', NULL, NULL, 14, 'Cakes', 'Compressed images/cake7.png'),
    (28, 'Pastel Delight Round Cake', NULL, NULL, 9, 'Cakes', 'Compressed images/cake4.png'),
    (29, 'Mocha Celebration Cake Round', NULL, NULL, 8, 'Cakes', 'Compressed images/cake11.png'),
    (30, 'Junior Cake, Ube Temptation', NULL, NULL, 9, 'Cakes', 'Compressed images/cake9.png'),
    (31, 'Choco Celebration On Cake Round', NULL, NULL, 7, 'Cakes', 'Compressed images/cake13.png'),
    (32, 'Yema Round Celebration On Cake', NULL, NULL, 9, 'Cakes', 'Compressed images/cake12.png'),
    (33, 'Choco Caramel Cake', NULL, NULL, 7, 'Cakes', 'Compressed images/cake1.png'),
    (34, 'Mocha Celebration On Cake Rectangle', NULL, NULL, 6, 'Cakes', 'Compressed images/cake15.png'),
    (35, 'Ube Macapuno Cake', NULL, NULL, 6, 'Cakes', 'Compressed images/cake6.png'),
    (36, 'Yema Rectangle Celebration On Cake', NULL, NULL, 4, 'Cakes', 'Compressed images/cake14.png'),
    (37, 'Roll Choco Fudge', NULL, NULL, 8, 'Cakes', 'Compressed images/cake17.png'),
    (38, 'Roll, Ube Macapuno', NULL, NULL, 14, 'Cakes', 'Compressed images/cake18.png'),
    (39, 'Roll, Nutty Caramel Cake', NULL, NULL, 18, 'Cakes', 'Compressed images/cake19.png'),
    (40, 'Junior Cake, Mango Cream Deluxe', NULL, NULL, 12, 'Cakes', 'Compressed images/cake10.png'),
    (41, 'Choco Celebration On Cake Rectangle', NULL, NULL, 13, 'Cakes', NULL),
    (42, 'Butterfly Sanctuary', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake20.png'),
    (43, 'Beauty Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake21.png'),
    (44, 'Space Adventure', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake36.png'),
    (45, 'Glitz’n Glam Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake22.png'),
    (46, 'Flamingo Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake24.png'),
    (47, 'Enchanted Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake23.png'),
    (48, 'Candy Drizzle Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake27.png'),
    (49, 'Cat Castle Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake25.png'),
    (50, 'Peppa Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake29.png'),
    (51, 'Ice Cream Heaven Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake30.png'),
    (52, 'Rainbow Unicorn', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake28.png'),
    (53, 'Princess Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake31.png'),
    (54, 'Blooming Flower Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake32.png'),
    (55, 'Elephant Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake34.png'),
    (56, 'Racers Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake39.png'),
    (57, 'Detective Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake38.png'),
    (58, 'Nautical Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake37.png'),
    (59, 'Sea Adventure Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake40.png'),
    (60, 'Jungle Explore Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake43.png'),
    (61, 'Nursery Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake44.png'),
    (62, 'Spider Web Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake46.png'),
    (63, 'Unicorn Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake26.png'),
    (64, 'Sonic Speed Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake42.png'),
    (65, 'Minecraft Kindom Cake', NULL, NULL, NULL, 'Cakes', 'Compressed images/cake41.png'),
    (66, 'Build The Party', NULL, NULL, NULL, 'Cakes', NULL);

INSERT INTO Inventory (Product_ID, Stock_Quantity) VALUES
    (1, 0),
    (2, 5),
    (3, 12),
    (4, 8),
    (5, 10),
    (6, 7),
    (7, 6),
    (8, 15),
    (9, 6),
    (10, 5),
    (11, 0),
    (12, 3),
    (13, 9),
    (14, 11),
    (15, 5),
    (16, 10),
    (17, 8),
    (18, 9),
    (19, 14),
    (20, 18),
    (21, 6),
    (22, 7),
    (23, 11),
    (24, 0),
    (25, 2),
    (26, 10),
    (27, 14),
    (28, 9),
    (29, 8),
    (30, 9),
    (31, 7),
    (32, 9),
    (33, 7),
    (34, 6),
    (35, 6),
    (36, 4),
    (37, 8),
    (38, 14),
    (39, 18),
    (40, 12),
    (41, 13),
    (42, NULL),
    (43, NULL),
    (44, NULL),
    (45, NULL),
    (46, NULL),
    (47, NULL),
    (48, NULL),
    (49, NULL),
    (50, NULL),
    (51, NULL),
    (52, NULL),
    (53, NULL),
    (54, NULL),
    (55, NULL),
    (56, NULL),
    (57, NULL),
    (58, NULL),
    (59, NULL),
    (60, NULL),
    (61, NULL),
    (62, NULL),
    (63, NULL),
    (64, NULL),
    (65, NULL),
    (66, NULL);
